// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.App = (function(_super) {
    __extends(App, _super);

    function App() {
      return App.__super__.constructor.apply(this, arguments);
    }

    App.prototype.initialize = function() {
      var deck;
      this.set('deck', deck = new Deck());
      this.set('playerHand', deck.dealPlayer());
      this.set('dealerHand', deck.dealDealer());
      this.attributes.playerHand.on('busted', this.dealerWins);
      this.attributes.dealerHand.on('busted', this.playerWins);
      return this.attributes.dealerHand.on('dealerStands', this.gameOver);
    };

    App.prototype.dealerPlays = function() {
      this.get('dealerHand').models[0].flip();
      return this.get('dealerHand').hit();
    };

    App.prototype.dealerWins = function() {
      return alert("Dealer wins");
    };

    App.prototype.playerWins = function() {
      return alert("Player wins");
    };

    App.prototype.gameOver = function() {
      return alert(this, "Game Over");
    };

    return App;

  })(Backbone.Model);

}).call(this);
